### PR TITLE
Refactor decoding

### PR DESCRIPTION
**Pull request by aedalzotto**
Still needs to test if area and timing are affected by this.

### CODE REVIEW

**Comment by aedalzotto** [comment]
2023-05-22T22:21:27,027643177-03:00
2023-05-22T22:17:05,223259735-03:00

Still not good enough

**Comment by aedalzotto** [comment]
Modified:
2023-05-23T17:24:38,987675613-03:00
2023-05-23T17:24:19,557470086-03:00

Baseline:
2023-05-23T17:30:57,742056104-03:00
2023-05-23T17:30:45,378612401-03:00

**Comment by aedalzotto** [comment]
2023-05-23T17:58:44,602278560-03:00
2023-05-23T17:58:33,823266035-03:00

Better now:
~3.7% decrease in LUT utilization
A bit of improvement in slack time, but I don't know if anything above 0 is meaningful (check [this](https://support.xilinx.com/s/question/0D52E000077tumHSAQ/which-one-is-better-high-or-low-positive-wns?language=en_US))

**Comment by aedalzotto** [comment]
2023-05-23T18:39:32,082707579-03:00
2023-05-23T18:39:19,814491456-03:00

Back to a little bit more LUTs but better timing.
I think the next step is changing instruction decoding to one-hot.

**Review by Willian-Nunes — APPROVED** [review]

**Comment by marlls1989** [comment]
How so? The slack is positive, timing is good.

**Pull request merged**
